let constants = {
    DEFAULT_DB: 'festumevento',
    MODELS: {
        admins: 'admins',
        executives: 'executives',
        subadmins: 'subadmins',
        superadmins: 'superadmins',
        organizers: 'organizers',
        users: 'users',
        events: 'events',
        eventreviews: 'eventreviews',
        offers: 'offers',
        items: 'items',
        eventcategories: 'eventcategories',
        shopcategories: 'shopcategories',
        discounts: 'discounts',
        shops: 'shops',
        onlineoffers: 'onlineoffers',
        offlineoffers: 'offlineoffers',
        notifications: 'notifications',
        promotionplans: 'promotionplans',
        customerimports: 'customerimports',
        settings: 'settings',
        notificationcoupons: 'notificationcoupons',
        platforms: 'platforms',
        livestreams : 'livestreams',
        livestreamreviews : 'livestreamreviews',
        livestreamwishlists : 'livestreamwishlists',
        subscriptions : 'subscriptions',
        eventwishlists : 'eventwishlists',
        shopreviews : 'shopreviews',
        offlineofferwishlists : 'offlineofferwishlists',
        onlineofferreviews : 'onlineofferreviews',
        onlineofferwishlists : 'onlineofferwishlists'
    }
};
module.exports = constants;
